### PR TITLE
Fix rock and roll hero styles

### PR DESCRIPTION
**Pull request by jacobarriola**
This fix attempts to address the issues on #26.

The logo was cutoff and different viewport sizes and was not centered.

To fix, explicit heights were removed as well as auto values for margin properties were applied. The logo became too big at larger viewports; as such, a max-width is applied to its container to ensure  the image and its subsequent hero do not become too wide as well as tall.

Also noticed the `background-size` property was missing, which was causing the background image to cutoff off at larger viewports.

Since the project utilizes Bourbon, I used their `margin` mixins.

### CODE REVIEW

**Comment by jorgelainfiesta** [comment]
It looks great! Thanks Jacob 😄

**Comment by taras** [comment]
Thank you @jacobarriola 👍

**Comment by jacobarriola** [comment]
Sweet! Thanks guys! 👏

**Comment by balinterdi** [comment]
Thank you, Jacob!

**Pull request merged**
